package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import hello.Sensor;
import hello.SensorRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/info")
public class MainController2 {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private SensorRepository sensorRepository;
	@GetMapping(path="/save") // Map ONLY GET Requests
	public @ResponseBody String addNewSensor (@RequestParam int idSensor
			, @RequestParam Double fecha,@RequestParam Double humedad,
			@RequestParam Double temperatura,@RequestParam Double co2 ) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		Sensor s = new Sensor();
		s.setFecha(fecha);
		s.setCo2(co2);
		s.setHumedad(humedad);
		s.setIdSensor(idSensor);
		s.setTemperatura(temperatura);
		sensorRepository.save(s);
		return "Saved";
	}
	
	@GetMapping(path="/See")
	public @ResponseBody Iterable<Sensor> getAllSensors() {
		// This returns a JSON or XML with the users
		return sensorRepository.findAll();
	}
}
